version: '3.6'
services:
  datasseq_dev:
    hostname: datasseq_dev
    build:
      context: .
      dockerfile: dockerfile
    image: datasseq2_testing
    #ports:
    #  - 81:4001

    healthcheck:
      test: curl --fail http://localhost:4001 || exit 1
      interval: 30s
      timeout: 10s

    networks:
      - datasseq_net_dev

    restart: always

networks:
 datasseq_net_dev:
    external: true
